config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  namespace :api, defaults: { format: :json } do
    post 'users/sign_in' => 'users#login'
    get 'users/:user_id/posts' => 'posts#index'
    get 'users/:user_id/posts/:post_id/comments' => 'comments#index'
    post 'posts/:post_id/comments/new' => 'comments#create'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "users#index"
  resources :users, only: %i[show index] do
    resources :posts, only: %i[show index new create destroy] do
      resources :comments, only: %i[new create destroy]
      resources :likes, only: %i[create]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= ::User.new
    can :read, :all # start by defining rules for all users, also not logged ones
    return unless user.present?

    can :manage, Post, author_id: user.id
    can :manage, Comment, author_id: user.id
    return unless user.role == 'admin'

    can :manage, :all # finally we give all remaining permissions only to the admins
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
require_relative 'application_record'

class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  after_save :update_comments_counter

  private

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
require_relative 'application_record'

class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  after_save :update_likes_counter

  private

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
require_relative 'application_record'

class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, foreign_key: 'post_id'
  has_many :likes, foreign_key: 'post_id'
  after_save :update_posts_counter
  validates :title, presence: true, length: { maximum: 250 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_nil: true
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_nil: true

  def recent_comments
    Comment.where(post_id: id).order('created_at DESC').limit(5)
  end

  private

  def update_posts_counter
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
require_relative 'application_record'

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  def recent_posts
    Post.where(author_id: id).order('created_at DESC').limit(3)
  end
  ROLES =
    def is?(requested_role)
      role == requested_role.to_s
    end
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < ApplicationController
  load_and_authorize_resource

  skip_before_action :verify_authenticity_token

  def index
    @comments = Comment.where(post_id: params[:post_id])
    render json: @comments
  end

  def create
    @user = User.find_by(api_token: params[:key])
    @comment = Comment.new(params.permit(:text, :post_id))
    @comment.author = @user
    if @comment.save
      flash[:success] = 'Comment created successfully'
      render json: @comment, status: :created
    else
      flash[:error] = 'Something went wrong'
      render json: @comment.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    @post = Post.find(@comment.post_id)
    @post.decrement!(:comments_counter)
    redirect_to @comment.post
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  load_and_authorize_resource except: :create
  def index
    @posts = Post.where(author_id: params[:user_id])
    render json: @posts
  end

  def show
    @post = Post.find(params[:id])
    @author = User.find(params[:user_id])
    @comments = Comment.where(post_id: params[:id])
    @comment = @post.comments.new
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comments }
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params.require(:post).permit(:title, :text))
    @post.author = current_user
    if @post.save
      flash[:success] = 'Post created successfully'
      redirect_to user_post_path(@post.author, @post)
    else
      flash.now[:error] = 'Something went wrong'
      render :new, status: 422
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.delete!
    redirect_to user_posts_path(@post.author), status: :see_other
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  skip_before_action :verify_authenticity_token
  def login
    valid = User.find_by(email: params[:email]).valid_password?(params[:password])
    if valid
      @user = User.find_by(email: params[:email])
      @user.api_token = Devise.friendly_token.to_s
      @user.save
      respond_to do |format|
        format.json { render json: @user.api_token, status: :ok }
      end
    else
      respond_to do |format|
        format.json { render json: 'Wrong email or password'.to_json, status: :ok }
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password password_confirmation])
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource except: :create
  def create
    puts params
    @comment = current_user.comments.new(params.require(:comment).permit(:text))
    @comment.post = Post.find(params[:post_id])
    if @comment.save
      flash[:success] = 'Comment created successfully'
    else
      flash[:error] = 'Something went wrong'
      puts 'error'
    end
    redirect_to user_post_path(@comment.post.author, @comment.post)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    @post = Post.find(@comment.post_id)
    @post.decrement!(:comments_counter)
    redirect_to @comment.post
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource except: :create
  def index
    @user = User.includes(:posts).find(params[:user_id])
    @posts = Post.where(author_id: params[:user_id])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  def show
    @post = Post.find(params[:id])
    @author = User.find(params[:user_id])
    @comments = Comment.where(post_id: params[:id])
    @comment = @post.comments.new
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comments }
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params.require(:post).permit(:title, :text))
    @post.author = current_user
    if @post.save
      flash[:success] = 'Post created successfully'
      redirect_to user_post_path(@post.author, @post)
    else
      flash.now[:error] = 'Something went wrong'
      render :new, status: 422
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.delete!
    redirect_to user_posts_path(@post.author), status: :see_other
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.recent_posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_newcomment.html.erb
<div class='commentformcontainer'>
  <h3>Leave a comment:</h3>
  <%= form_with model: @comment, url: user_post_comments_path(@post.author.id, @post.id) do |f| %>
    <%= f.text_area :text %><br>
    <%= f.submit "Post Comment"%>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "turbo", type: "module" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
  <body>
    <div class='container'>
      <div class='card'>
        <img class='userpic' src= <%= @user.photo %> >
        <div class='leftcard'>
          <h2 class='username'><%= @user.name %></h2>
          <p class='count'>Number of posts: <%= @user.posts_counter || '0' %></p><br>
        </div>
      </div>
        <% @user.posts.each do |post| %>
          <a href=<%= user_post_url(@user.id, post.id) %> class='subcontainer'>
            <div class='postcard'>
              <p><%= post.title %></p>
              <p><%= post.text.truncate(50, separator:' ') %></p>
              <p class='count'>
                Comments: <%= post.comments_counter || '0' %>
                Likes: <%= post.likes_counter || '0' %>
              </p>
              <% if can? :manage, post %>
                <%= link_to 'Delete Post', user_post_path(@user.id, post.id), method: :delete, form: {data: {turbo_confirm: 'Are you sure?', turbo_method: :delete}} %>
              <% end %>
            </div>
            <% @comments = post.recent_comments %>
            <% if @comments.length > 0 %>
              <div class='commentscard'>
                <% @comments.includes(:author).each do |comment| %>
                  <p class='comment'><%= comment.author.name %>: <%= comment.text %></p>
                <% end %>
              </div>
            <% end %>
          </a>
        <% end %>
      
      <a class='button'>Pagination(Not Working)</a>
    </div>
  </body>

app/views/posts/new.html.erb
  <body>
    <div class='container'>
      <h2>New Post:</h2>
      <%= form_with model: @post, url: user_posts_path, method: :post do |f| %>
        <%= f.label :title %>
        <%= f.text_field :title %>
        <%= f.label :text %>
        <%= f.text_area :text %>
        <%= f.submit "Create Post" %>
      <% end %>
    </div>
  </body>

app/views/posts/show.html.erb
  <body>
    <div class='container postscreen'>
      <div class='postcard'>
        <h2><%= @post.title %> by <%= @author.name %></h2>
        <p class='count'>
          Comments: <%= @post.comments_counter || '0' %>
          Likes: <%= @post.likes_counter || '0' %>
        </p>
        <p><%= @post.text %></p>
        <% if can? :manage, @post %>
          <%= link_to 'Delete Post', user_post_path(@author.id, @post.id), method: :delete, form: {data: {turbo_confirm: 'Are you sure?', turbo_method: :delete}} %>
        <% end %>
      </div>
      <% if @comments.length > 0 %>
        <div class='commentscard'>
          <% @comments.includes(:author).each do |comment| %>
            <p class='comment'><%= comment.author.name %>: <%= comment.text %></p>
            <% if can? :manage, comment %>
              <%= link_to 'Delete', user_post_comment_path(@author.id, @post.id, comment.id), method: :delete, form: {data: {turbo_confirm: 'Are you sure?', turbo_method: :delete}} %>
            <% end %>
          <% end %>
        </div>
      <% end %>
      <%= render 'comments/newcomment' %>
    </div>
  </body>

app/views/users/index.html.erb
  <body>
    <div class='topbar'>
      <% if user_signed_in? %>
      <div class='button small'>
        <%= link_to(destroy_user_session_path, {:class => "nav-link", :method => :delete}) do  %>
          <span class="sidebar-normal"> Logout </span>
        <% end %>
      </div>
      <div class='button small'>
        <%= link_to "post", new_user_post_path(current_user.id)%>
      </div>
      <p><%= current_user.name %></p>
    <% else %>
      <div class='button small'>
        <%= link_to "login", new_user_session_path %>
      </div>
    <% end %>
    </div>
    <div class='container'>
      <% @users.each do |user| %>
        <div class='card'>
          <img class='userpic' src= <%= user.photo %> >
          <a href="<%= user_url(user.id) %>" class='leftcard'>
            <h2 class='username'><%= user.name %></h2>
            <p class='count'>Number of posts: <%= user.posts_counter || '0' %></p><br>
          </a>
        </div>
      <% end %>
    </div>
  </body>

app/views/users/show.html.erb
  <body>
    <div class='container'>
      <div class='card'>
        <img class='userpic' src= <%= @user.photo %> >
        <div class='leftcard'>
          <h2 class='username'><%= @user.name %></h2>
          <p class='count'>Number of posts: <%= @user.posts_counter || '0' %></p><br>
        </div>
      </div>
      <div class='biodiv'>
        <p>Bio</p>
        <p><%= @user.bio %></p>
      </div>
      <% @posts.each do |post| %>
        <a href=<%= user_post_url(@user.id, post.id) %> >
          <div class='postcard'>
            <p><%= post.title %></p>
            <p><%= post.text.truncate(50, separator:' ') %></p>
            <p class='count'>
              Comments: <%= post.comments_counter || '0' %>
              Likes: <%= post.likes_counter || '0' %>
            </p>
          </div>
        </a>
      <% end %>
      <a class='button' href=<%= user_posts_url(@user.id)%>>See All Posts</a>
    </div>
  </body>